apiVersion: v1
kind: Pod
metadata:
  name: stao-access # replace with "${USER_NAME}-{POD_NAME}"
  namespace: ucsd-haosulab
spec:
  containers:
    - name: access-container
      image: gitlab-registry.nrp-nautilus.io/stonet2000/boxpusher # docker image
      # imagePullPolicy: Always
      command:
        - bash
        - -c
        - |
          eval "$(/opt/conda/bin/conda shell.bash hook)"
          sleep infinity
      resources:
        requests:
          cpu: "2"
          memory: "12Gi"
          nvidia.com/gpu: "0"
        limits:
          cpu: "2"
          memory: "12Gi"
          nvidia.com/gpu: "0"
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: cephfs
          mountPath: /cephfs
        - mountPath: /stao-fast-vol
          name: stao-fast-vol
        - mountPath: /stao-fast-vol-1
          name: stao-fast-vol-1
        - mountPath: /stao-slow-vol-1
          name: stao-slow-vol-1
  volumes:
    - name: dshm # shared memory, required for the multi-worker dataloader
      emptyDir:
        medium: Memory
    - name: cephfs
      persistentVolumeClaim:
        claimName: haosulab-cephfs
    - name: stao-fast-vol
      persistentVolumeClaim:
        claimName: stao-fast-vol
    - name: stao-fast-vol-1
      persistentVolumeClaim:
        claimName: stao-fast-vol-1
    - name: stao-slow-vol-1
      persistentVolumeClaim:
        claimName: stao-slow-vol-1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nautilus.io/group
                operator: In
                values:
                  - haosu
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-2080-Ti